/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author James
 */
public class Gui extends javax.swing.JPanel {

    Hotel mainHotel = new Hotel();


        /**
     * Creates new form TestResultListPanel
     */
    public Gui() {
        initComponents();

    }
    public static void main(String[] args){
        Gui hotel = new Gui();
        JFrame hotelFrame = new JFrame();
        hotelFrame.add(hotel);
        hotelFrame.setVisible(true);
        hotelFrame.setSize(500, 600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {









        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel7.setText("Guest Information");

        jLabel8.setText("Last Name");

        jLabel9.setText("First Name");


        jTextField2.addActionListener(this::jTextField2ActionPerformed);


        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel1.setText("Address");


        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel2.setText("City");


        jTextField4.addActionListener(this::jTextField4ActionPerformed);


        jLabel3.setText("State");


        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jLabel4.setText("Zip");


        jTextField6.addActionListener(this::jTextField6ActionPerformed);
        jTextField8.addActionListener(this::jTextField8ActionPerformed);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Male", "Female"}));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel5.setText("Gender");

        jLabel6.setText("Country");
        String[] locales = Locale.getISOCountries();
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(locales));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        jLabel10.setText("Email");


        jTextField7.addActionListener(this::jTextField7ActionPerformed);

        jLabel11.setText("Phone");




        jLabel12.setText("Birth Date");


        jTextField9.addActionListener((actionEvent) -> {
            try {
                jTextField9ActionPerformed(actionEvent);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        });

        jLabel14.setText("Settlement Option");

        jLabel13.setText("Type");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Visa", "Mastercard", "Amex", "American Express"}));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);

        jLabel15.setText("Card No");


        jTextField10.addActionListener(this::jTextField10ActionPerformed);

        jLabel16.setText("Bill To");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Guest", "Company"}));
        jComboBox4.addActionListener(this::jComboBox4ActionPerformed);

        jLabel17.setText("Expire");


        jTextField11.addActionListener((actionEvent) -> {
            try {
                jTextField11ActionPerformed(actionEvent);
            } catch (ParseException e) {
                e.printStackTrace();
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jButton1.setText("Save");
        jButton1.addActionListener(e -> jButton1ActionPerformed());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(22, 22, 22)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jButton1)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(jLabel14)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(jLabel15)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(jLabel8))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)

                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(jLabel3))
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(jLabel5)))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jTextField10)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel17)
                                                                                                .addGap(18, 18, 18)

                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addComponent(jSeparator9))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSeparator2))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))

                                )
                                .addContainerGap(278, Short.MAX_VALUE))

        );

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel8)
                                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel9)
                                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel5))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                                                                                .addComponent(jLabel6)
                                                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel10)
                                                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel11)
                                                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel13)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        )
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel16)
                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        )


        );

    }// </editor-fold>

    private void jTextField2ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setLastName(jTextField2.getText());

    }





    private void jTextField1ActionPerformed(ActionEvent actionEvent) {
        String s = jTextField1.getText();
        System.out.println(s);
    }
    private void jButton1ActionPerformed(){
        mainHotel.guest.setFirstName(jTextField1.getText());
        mainHotel.guest.setLastName(jTextField2.getText());
        mainHotel.guest.setAddress(jTextField3.getText());
        mainHotel.guest.setCity(jTextField4.getText());
        mainHotel.guest.setState(jTextField5.getText());
        mainHotel.guest.setTelephoneNumber(Long.parseLong(jTextField8.getSelectedText()));
        mainHotel.guest.setZip(Integer.parseInt(jTextField6.getText()));
        mainHotel.guest.setGender((String) jComboBox1.getSelectedItem());
        mainHotel.guest.setCountry((String) jComboBox2.getSelectedItem());
        mainHotel.guest.setEmail(jTextField7.getText());

        mainHotel.guest.card.setCreditCardType((String) jComboBox3.getSelectedItem());
        mainHotel.guest.card.setCardNumber(Integer.parseInt(jTextField10.getText()));
        System.out.println(mainHotel.guest.getLastName()
                + "\n" + mainHotel.guest.getFirstName()
                + "\n" + mainHotel.guest.getAddress()
                + "\n" + mainHotel.guest.getCity()
                + "\n" + mainHotel.guest.getState()
                + "\n" + mainHotel.guest.getZip()
                + "\n" + mainHotel.guest.getGender()
                + "\n" + mainHotel.guest.getCountry()
                + "\n" + mainHotel.guest.getEmail()
                + "\n");
        System.out.println( mainHotel.guest.getTelephoneNumber());
    }
    private void jTextField3ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setAddress(jTextField3.getText());

    }

    private void jTextField4ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setCity(jTextField4.getText());
    }

    private void jTextField5ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setState(jTextField5.getText());
    }

    private void jTextField6ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setZip(Integer.parseInt(jTextField6.getText()));
    }

    private void jTextField8ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setTelephoneNumber(Long.parseLong(jTextField8.getText()));
    }

    private void jComboBox1ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setGender((String) jComboBox1.getSelectedItem());

    }

    private void jComboBox2ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.setCountry((String) jComboBox2.getSelectedItem());
    }

    private void jTextField7ActionPerformed(ActionEvent actionEvent) {
       mainHotel.guest.setEmail(jTextField7.getText());
    }



    private void jTextField9ActionPerformed(ActionEvent actionEvent) throws ParseException {
        DateFormat format = new SimpleDateFormat("MM/d/yy", Locale.ENGLISH);
        mainHotel.guest.setBirthDate(format.parse(jTextField9.getText()));
    }

    private void jComboBox3ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.card.setCreditCardType((String) jComboBox3.getSelectedItem());

    }

    private void jTextField10ActionPerformed(ActionEvent actionEvent) {
        mainHotel.guest.card.setCardNumber(Integer.parseInt(jTextField10.getText()));
    }

    private void jTextField11ActionPerformed(ActionEvent actionEvent) throws ParseException{
        DateFormat format = new SimpleDateFormat("MM/yy", Locale.ENGLISH);
        mainHotel.guest.setBirthDate(format.parse(jTextField11.getText()));
    }

    private void jComboBox4ActionPerformed(ActionEvent actionEvent) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    JDialog jDialog1 = new JDialog();

    JLabel jLabel1 = new JLabel();

    JLabel jLabel6 = new JLabel();

    JLabel jLabel10 = new JLabel();

    JLabel jLabel11 = new JLabel();

    JLabel jLabel12 = new JLabel();

    JLabel jLabel16 = new JLabel();


    JComboBox jComboBox1 = new JComboBox();
    JComboBox jComboBox2 = new JComboBox();
    JComboBox jComboBox3 = new JComboBox();
    JComboBox jComboBox4 = new JComboBox();
    JLabel jLabel13 = new JLabel();
    JLabel jLabel14 = new JLabel();
    JLabel jLabel15 = new JLabel();
    JLabel jLabel17 = new JLabel();
    JLabel jLabel2  = new JLabel();
    JLabel jLabel3  = new JLabel();
    JLabel jLabel4  = new JLabel();
    JLabel jLabel5  = new JLabel();
    JLabel jLabel7  = new JLabel();
    JLabel jLabel8  = new JLabel();
    JLabel jLabel9  = new JLabel();
    JSeparator jSeparator1 = new JSeparator();
    JSeparator jSeparator2 = new JSeparator();
    JSeparator jSeparator3 = new JSeparator();
    JSeparator jSeparator4 = new JSeparator();
    JSeparator jSeparator5 = new JSeparator();
    JSeparator jSeparator6 = new JSeparator();
    JSeparator jSeparator7 = new JSeparator();
    JSeparator jSeparator8 = new JSeparator();
    JSeparator jSeparator9 = new JSeparator();
    JTextField jTextField1 = new JTextField();
    JTextField jTextField10 = new JTextField();
    JTextField jTextField11 = new JTextField();
    JTextField jTextField2 = new JTextField();
    JTextField jTextField3 = new JTextField();
    JTextField jTextField4 = new JTextField();
    JTextField jTextField5 = new JTextField();
    JTextField jTextField6= new JTextField();
    JTextField jTextField7= new JTextField();
    JTextField jTextField8= new JTextField();
    JTextField jTextField9= new JTextField();
    JButton jButton1 = new JButton();

    // End of variables declaration


}

